package com.burlingamerobotics.scouting.common

import java.util.*

const val API_KEY_TBA = "eeszr95mLfyCJkDqDrXAxsW93MgRYrmn8lLqrUJ76GfSYIWNxA8N5mCUILlX3dFN"

const val PROTOCOL_VERSION = "1.0.07"

val SCOUTING_UUID = UUID.nameUUIDFromBytes("ironpanthers-scouting-v${PROTOCOL_VERSION}".toByteArray())

const val URL_TBA_API = "https://www.thebluealliance.com/api/v3/"

const val INTENT_START_CLIENT_ATTACH_TO_LOCAL = "START_CLIENT_ATTACHED_TO_LOCAL"

const val INTENT_BIND_LOCAL_CLIENT_TO_SERVER = "BIND_LOCAL_CLIENT_TO_SERVER"

const val INTENT_CLIENT_CONNECTED = "CLIENT_CONNECTED"
const val INTENT_CLIENT_DISCONNECTED = "CLIENT_DISCONNECTED"
const val INTENT_START_SCOUTING_SERVER = "START_SCOUTING_SERVER"

const val REQUEST_CODE_NEW_COMPETITION = 2356847
const val REQUEST_CODE_EDIT_COMPETITION = 930214785

const val DURATION_SAVE_DATA = 120000L